# Generated by Django 3.2.7 on 2022-12-05 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Event_lent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Free_vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=127)),
                ('period', models.CharField(max_length=127)),
                ('requirements', models.TextField()),
                ('responsibilities', models.TextField()),
                ('you_ll_recive', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Our_partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('position', models.CharField(max_length=127)),
                ('experience', models.CharField(max_length=127)),
                ('activity', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='Type_of_work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.TextField()),
                ('type_of_work_name', models.CharField(max_length=127)),
                ('type_of_work', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_project', models.CharField(max_length=127)),
                ('stage', models.CharField(max_length=127)),
                ('stuff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stuff', to='info.stuff')),
            ],
        ),
    ]
